// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_protoc.proto

package scheduler

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SchedNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SelfIPAddress        string   `protobuf:"bytes,2,opt,name=SelfIPAddress,proto3" json:"SelfIPAddress,omitempty"`
	EstablishedConnIP    []string `protobuf:"bytes,3,rep,name=EstablishedConnIP,proto3" json:"EstablishedConnIP,omitempty"`
	RemainingConnIP      []string `protobuf:"bytes,4,rep,name=RemainingConnIP,proto3" json:"RemainingConnIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchedNameRequest) Reset()         { *m = SchedNameRequest{} }
func (m *SchedNameRequest) String() string { return proto.CompactTextString(m) }
func (*SchedNameRequest) ProtoMessage()    {}
func (*SchedNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_74f365089891a3f3, []int{0}
}

func (m *SchedNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedNameRequest.Unmarshal(m, b)
}
func (m *SchedNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedNameRequest.Marshal(b, m, deterministic)
}
func (m *SchedNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedNameRequest.Merge(m, src)
}
func (m *SchedNameRequest) XXX_Size() int {
	return xxx_messageInfo_SchedNameRequest.Size(m)
}
func (m *SchedNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SchedNameRequest proto.InternalMessageInfo

func (m *SchedNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SchedNameRequest) GetSelfIPAddress() string {
	if m != nil {
		return m.SelfIPAddress
	}
	return ""
}

func (m *SchedNameRequest) GetEstablishedConnIP() []string {
	if m != nil {
		return m.EstablishedConnIP
	}
	return nil
}

func (m *SchedNameRequest) GetRemainingConnIP() []string {
	if m != nil {
		return m.RemainingConnIP
	}
	return nil
}

type SchedNameResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EstablishedConnIP    []string `protobuf:"bytes,3,rep,name=EstablishedConnIP,proto3" json:"EstablishedConnIP,omitempty"`
	RemainingConnIP      []string `protobuf:"bytes,4,rep,name=RemainingConnIP,proto3" json:"RemainingConnIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchedNameResponse) Reset()         { *m = SchedNameResponse{} }
func (m *SchedNameResponse) String() string { return proto.CompactTextString(m) }
func (*SchedNameResponse) ProtoMessage()    {}
func (*SchedNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_74f365089891a3f3, []int{1}
}

func (m *SchedNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedNameResponse.Unmarshal(m, b)
}
func (m *SchedNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedNameResponse.Marshal(b, m, deterministic)
}
func (m *SchedNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedNameResponse.Merge(m, src)
}
func (m *SchedNameResponse) XXX_Size() int {
	return xxx_messageInfo_SchedNameResponse.Size(m)
}
func (m *SchedNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchedNameResponse proto.InternalMessageInfo

func (m *SchedNameResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SchedNameResponse) GetEstablishedConnIP() []string {
	if m != nil {
		return m.EstablishedConnIP
	}
	return nil
}

func (m *SchedNameResponse) GetRemainingConnIP() []string {
	if m != nil {
		return m.RemainingConnIP
	}
	return nil
}

type UpdateResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EstablishedConnIP    []string `protobuf:"bytes,3,rep,name=EstablishedConnIP,proto3" json:"EstablishedConnIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_74f365089891a3f3, []int{2}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateResponse) GetEstablishedConnIP() []string {
	if m != nil {
		return m.EstablishedConnIP
	}
	return nil
}

type NodeInfo struct {
	NodeName             string               `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Duration             float64              `protobuf:"fixed64,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Sign                 int32                `protobuf:"varint,3,opt,name=sign,proto3" json:"sign,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SchedulerName        string               `protobuf:"bytes,5,opt,name=scheduler_name,json=schedulerName,proto3" json:"scheduler_name,omitempty"`
	PodName              string               `protobuf:"bytes,6,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_74f365089891a3f3, []int{3}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *NodeInfo) GetDuration() float64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *NodeInfo) GetSign() int32 {
	if m != nil {
		return m.Sign
	}
	return 0
}

func (m *NodeInfo) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *NodeInfo) GetSchedulerName() string {
	if m != nil {
		return m.SchedulerName
	}
	return ""
}

func (m *NodeInfo) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

type NodeInfoResponse struct {
	Done                 bool                 `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SchedulerName        string               `protobuf:"bytes,3,opt,name=scheduler_name,json=schedulerName,proto3" json:"scheduler_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NodeInfoResponse) Reset()         { *m = NodeInfoResponse{} }
func (m *NodeInfoResponse) String() string { return proto.CompactTextString(m) }
func (*NodeInfoResponse) ProtoMessage()    {}
func (*NodeInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_74f365089891a3f3, []int{4}
}

func (m *NodeInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfoResponse.Unmarshal(m, b)
}
func (m *NodeInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfoResponse.Marshal(b, m, deterministic)
}
func (m *NodeInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfoResponse.Merge(m, src)
}
func (m *NodeInfoResponse) XXX_Size() int {
	return xxx_messageInfo_NodeInfoResponse.Size(m)
}
func (m *NodeInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfoResponse proto.InternalMessageInfo

func (m *NodeInfoResponse) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *NodeInfoResponse) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *NodeInfoResponse) GetSchedulerName() string {
	if m != nil {
		return m.SchedulerName
	}
	return ""
}

type InitialUpdate struct {
	NewIpConnected       string   `protobuf:"bytes,1,opt,name=new_ip_connected,json=newIpConnected,proto3" json:"new_ip_connected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitialUpdate) Reset()         { *m = InitialUpdate{} }
func (m *InitialUpdate) String() string { return proto.CompactTextString(m) }
func (*InitialUpdate) ProtoMessage()    {}
func (*InitialUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_74f365089891a3f3, []int{5}
}

func (m *InitialUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitialUpdate.Unmarshal(m, b)
}
func (m *InitialUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitialUpdate.Marshal(b, m, deterministic)
}
func (m *InitialUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialUpdate.Merge(m, src)
}
func (m *InitialUpdate) XXX_Size() int {
	return xxx_messageInfo_InitialUpdate.Size(m)
}
func (m *InitialUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_InitialUpdate proto.InternalMessageInfo

func (m *InitialUpdate) GetNewIpConnected() string {
	if m != nil {
		return m.NewIpConnected
	}
	return ""
}

type InitialResponse struct {
	Done                 bool     `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitialResponse) Reset()         { *m = InitialResponse{} }
func (m *InitialResponse) String() string { return proto.CompactTextString(m) }
func (*InitialResponse) ProtoMessage()    {}
func (*InitialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_74f365089891a3f3, []int{6}
}

func (m *InitialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitialResponse.Unmarshal(m, b)
}
func (m *InitialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitialResponse.Marshal(b, m, deterministic)
}
func (m *InitialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialResponse.Merge(m, src)
}
func (m *InitialResponse) XXX_Size() int {
	return xxx_messageInfo_InitialResponse.Size(m)
}
func (m *InitialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitialResponse proto.InternalMessageInfo

func (m *InitialResponse) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type Heartbeat struct {
	Alive                bool     `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_74f365089891a3f3, []int{7}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func init() {
	proto.RegisterType((*SchedNameRequest)(nil), "scheduler.SchedNameRequest")
	proto.RegisterType((*SchedNameResponse)(nil), "scheduler.SchedNameResponse")
	proto.RegisterType((*UpdateResponse)(nil), "scheduler.UpdateResponse")
	proto.RegisterType((*NodeInfo)(nil), "scheduler.NodeInfo")
	proto.RegisterType((*NodeInfoResponse)(nil), "scheduler.NodeInfoResponse")
	proto.RegisterType((*InitialUpdate)(nil), "scheduler.InitialUpdate")
	proto.RegisterType((*InitialResponse)(nil), "scheduler.InitialResponse")
	proto.RegisterType((*Heartbeat)(nil), "scheduler.Heartbeat")
}

func init() {
	proto.RegisterFile("server_protoc.proto", fileDescriptor_74f365089891a3f3)
}

var fileDescriptor_74f365089891a3f3 = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x8d, 0xf3, 0xd3, 0x2f, 0xbe, 0x5f, 0x9b, 0xa6, 0xd3, 0x20, 0xb9, 0x0e, 0x12, 0x61, 0x44,
	0x25, 0x2f, 0x90, 0x2b, 0x95, 0x0d, 0x2c, 0x69, 0xf9, 0x8b, 0x90, 0x4a, 0xe5, 0xc0, 0x86, 0x4d,
	0x34, 0xc9, 0xdc, 0xa4, 0x23, 0x39, 0x33, 0xc6, 0x33, 0x69, 0x97, 0x2c, 0x79, 0x11, 0xde, 0x88,
	0x87, 0x61, 0x8b, 0x3c, 0xfe, 0xc1, 0x69, 0xa3, 0x6e, 0x80, 0x55, 0xc6, 0xe7, 0x9c, 0xb9, 0x39,
	0xf7, 0xde, 0x63, 0xc3, 0xa1, 0xc6, 0xf4, 0x1a, 0xd3, 0x69, 0x92, 0x2a, 0xa3, 0xe6, 0xa1, 0xfd,
	0x21, 0xae, 0x9e, 0x5f, 0x21, 0x5f, 0xc7, 0x98, 0xfa, 0x8f, 0x96, 0x4a, 0x2d, 0x63, 0x3c, 0xb1,
	0xc4, 0x6c, 0xbd, 0x38, 0x31, 0x62, 0x85, 0xda, 0xb0, 0x55, 0x92, 0x6b, 0xe9, 0x77, 0x07, 0xfa,
	0x93, 0x4c, 0x7e, 0xc1, 0x56, 0x18, 0xe1, 0x97, 0x35, 0x6a, 0x43, 0x08, 0xb4, 0x25, 0x5b, 0xa1,
	0xe7, 0x8c, 0x9c, 0xc0, 0x8d, 0xec, 0x99, 0x3c, 0x81, 0xbd, 0x09, 0xc6, 0x8b, 0xf1, 0xe5, 0x4b,
	0xce, 0x53, 0xd4, 0xda, 0x6b, 0x5a, 0x72, 0x13, 0x24, 0x4f, 0xe1, 0xe0, 0xb5, 0x36, 0x6c, 0x16,
	0x0b, 0x7d, 0x85, 0xfc, 0x5c, 0x49, 0x39, 0xbe, 0xf4, 0x5a, 0xa3, 0x56, 0xe0, 0x46, 0x77, 0x09,
	0x12, 0xc0, 0x7e, 0x84, 0x2b, 0x26, 0xa4, 0x90, 0xcb, 0x42, 0xdb, 0xb6, 0xda, 0xdb, 0x30, 0xfd,
	0x0a, 0x07, 0x35, 0x97, 0x3a, 0x51, 0x52, 0xe3, 0x56, 0x9b, 0xff, 0xca, 0x40, 0x04, 0xbd, 0x4f,
	0x09, 0x67, 0xe6, 0x2f, 0xfe, 0x3b, 0xfd, 0xe1, 0x40, 0xf7, 0x42, 0x71, 0x1c, 0xcb, 0x85, 0x22,
	0x43, 0x70, 0xa5, 0xe2, 0x38, 0xad, 0xd5, 0xec, 0x66, 0x40, 0xd6, 0x31, 0xf1, 0xa1, 0xcb, 0xd7,
	0x29, 0x33, 0x42, 0x49, 0x3b, 0x77, 0x27, 0xaa, 0x9e, 0x33, 0x1f, 0x5a, 0x2c, 0xa5, 0xd7, 0x1a,
	0x39, 0x41, 0x27, 0xb2, 0x67, 0xf2, 0x1c, 0xdc, 0x6a, 0xd1, 0x5e, 0x7b, 0xe4, 0x04, 0xff, 0x9f,
	0xfa, 0x61, 0x1e, 0x85, 0xb0, 0x8c, 0x42, 0xf8, 0xb1, 0x54, 0x44, 0xbf, 0xc5, 0xe4, 0x18, 0x7a,
	0x55, 0x7a, 0x72, 0x2f, 0x9d, 0x7c, 0xcf, 0x15, 0x6a, 0x0d, 0x1d, 0x41, 0x37, 0x51, 0x3c, 0x17,
	0xec, 0x58, 0xc1, 0x7f, 0x89, 0xb2, 0xdb, 0xa1, 0xdf, 0x1c, 0xe8, 0x97, 0x5d, 0xd5, 0x87, 0xc5,
	0x95, 0xcc, 0x1b, 0xeb, 0x46, 0xf6, 0xbc, 0x69, 0xb2, 0xf9, 0x67, 0x26, 0x5b, 0x5b, 0x4c, 0xd2,
	0x17, 0xb0, 0x37, 0x96, 0xc2, 0x08, 0x16, 0xe7, 0xab, 0x23, 0x01, 0xf4, 0x25, 0xde, 0x4c, 0x45,
	0x32, 0x9d, 0x2b, 0x29, 0x71, 0x6e, 0x90, 0x17, 0xa3, 0xee, 0x49, 0xbc, 0x19, 0x27, 0xe7, 0x25,
	0x4a, 0x8f, 0x61, 0xbf, 0xb8, 0x7a, 0x5f, 0x0b, 0xf4, 0x31, 0xb8, 0xef, 0x90, 0xa5, 0x66, 0x86,
	0xcc, 0x90, 0x01, 0x74, 0x58, 0x2c, 0xae, 0x4b, 0x45, 0xfe, 0x70, 0xfa, 0xb3, 0x09, 0x1d, 0x1b,
	0x5d, 0xf2, 0x1e, 0x76, 0xdf, 0xa2, 0xa9, 0x62, 0x4c, 0x86, 0x61, 0x65, 0x37, 0xbc, 0xfd, 0x0a,
	0xfa, 0x0f, 0xb7, 0x93, 0xb9, 0x17, 0xda, 0x20, 0x6f, 0x00, 0xb2, 0x37, 0xaf, 0x68, 0xec, 0xde,
	0x52, 0x47, 0x35, 0x72, 0x33, 0xc3, 0xb4, 0x41, 0xce, 0x60, 0x77, 0x82, 0x92, 0x57, 0x31, 0x3c,
	0xac, 0x89, 0x4b, 0xd0, 0x1f, 0x6e, 0x01, 0x6b, 0x35, 0x3e, 0xc0, 0x83, 0xac, 0x46, 0x31, 0xb0,
	0x62, 0x88, 0x59, 0x34, 0xbd, 0xda, 0xbd, 0x8d, 0x4d, 0xf8, 0xfe, 0x5d, 0xa6, 0x56, 0xf0, 0x15,
	0x0c, 0xb2, 0x82, 0xd5, 0x68, 0xcb, 0xef, 0xd2, 0xa0, 0x76, 0xab, 0x22, 0xfd, 0xad, 0x28, 0x6d,
	0x9c, 0xb5, 0x3e, 0x3b, 0xe1, 0x6c, 0xc7, 0x26, 0xe9, 0xd9, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa7, 0x46, 0xda, 0x2a, 0x29, 0x05, 0x00, 0x00,
}
