// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: server_protoctest.proto

package scheduler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SchedClient is the client API for Sched service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedClient interface {
	GetSchedName(ctx context.Context, in *SchedNameRequest, opts ...grpc.CallOption) (*SchedNameResponse, error)
	SelfUpdate(ctx context.Context, in *SchedNameRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type schedClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedClient(cc grpc.ClientConnInterface) SchedClient {
	return &schedClient{cc}
}

func (c *schedClient) GetSchedName(ctx context.Context, in *SchedNameRequest, opts ...grpc.CallOption) (*SchedNameResponse, error) {
	out := new(SchedNameResponse)
	err := c.cc.Invoke(ctx, "/scheduler.Sched/GetSchedName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedClient) SelfUpdate(ctx context.Context, in *SchedNameRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/scheduler.Sched/SelfUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedServer is the server API for Sched service.
// All implementations must embed UnimplementedSchedServer
// for forward compatibility
type SchedServer interface {
	GetSchedName(context.Context, *SchedNameRequest) (*SchedNameResponse, error)
	SelfUpdate(context.Context, *SchedNameRequest) (*UpdateResponse, error)
	mustEmbedUnimplementedSchedServer()
}

// UnimplementedSchedServer must be embedded to have forward compatible implementations.
type UnimplementedSchedServer struct {
}

func (UnimplementedSchedServer) GetSchedName(context.Context, *SchedNameRequest) (*SchedNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchedName not implemented")
}
func (UnimplementedSchedServer) SelfUpdate(context.Context, *SchedNameRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelfUpdate not implemented")
}
func (UnimplementedSchedServer) mustEmbedUnimplementedSchedServer() {}

// UnsafeSchedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedServer will
// result in compilation errors.
type UnsafeSchedServer interface {
	mustEmbedUnimplementedSchedServer()
}

func RegisterSchedServer(s grpc.ServiceRegistrar, srv SchedServer) {
	s.RegisterService(&Sched_ServiceDesc, srv)
}

func _Sched_GetSchedName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedServer).GetSchedName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler.Sched/GetSchedName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedServer).GetSchedName(ctx, req.(*SchedNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sched_SelfUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedServer).SelfUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduler.Sched/SelfUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedServer).SelfUpdate(ctx, req.(*SchedNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sched_ServiceDesc is the grpc.ServiceDesc for Sched service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sched_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.Sched",
	HandlerType: (*SchedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSchedName",
			Handler:    _Sched_GetSchedName_Handler,
		},
		{
			MethodName: "SelfUpdate",
			Handler:    _Sched_SelfUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server_protoctest.proto",
}
