// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_protoctest.proto

package scheduler

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SchedNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SelfIPAddress        string   `protobuf:"bytes,2,opt,name=SelfIPAddress,proto3" json:"SelfIPAddress,omitempty"`
	EstablishedConnIP    []string `protobuf:"bytes,3,rep,name=EstablishedConnIP,proto3" json:"EstablishedConnIP,omitempty"`
	RemainingConnIP      []string `protobuf:"bytes,4,rep,name=RemainingConnIP,proto3" json:"RemainingConnIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchedNameRequest) Reset()         { *m = SchedNameRequest{} }
func (m *SchedNameRequest) String() string { return proto.CompactTextString(m) }
func (*SchedNameRequest) ProtoMessage()    {}
func (*SchedNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61f52ad2bbf7fb36, []int{0}
}

func (m *SchedNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedNameRequest.Unmarshal(m, b)
}
func (m *SchedNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedNameRequest.Marshal(b, m, deterministic)
}
func (m *SchedNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedNameRequest.Merge(m, src)
}
func (m *SchedNameRequest) XXX_Size() int {
	return xxx_messageInfo_SchedNameRequest.Size(m)
}
func (m *SchedNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SchedNameRequest proto.InternalMessageInfo

func (m *SchedNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SchedNameRequest) GetSelfIPAddress() string {
	if m != nil {
		return m.SelfIPAddress
	}
	return ""
}

func (m *SchedNameRequest) GetEstablishedConnIP() []string {
	if m != nil {
		return m.EstablishedConnIP
	}
	return nil
}

func (m *SchedNameRequest) GetRemainingConnIP() []string {
	if m != nil {
		return m.RemainingConnIP
	}
	return nil
}

type SchedNameResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EstablishedConnIP    []string `protobuf:"bytes,3,rep,name=EstablishedConnIP,proto3" json:"EstablishedConnIP,omitempty"`
	RemainingConnIP      []string `protobuf:"bytes,4,rep,name=RemainingConnIP,proto3" json:"RemainingConnIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchedNameResponse) Reset()         { *m = SchedNameResponse{} }
func (m *SchedNameResponse) String() string { return proto.CompactTextString(m) }
func (*SchedNameResponse) ProtoMessage()    {}
func (*SchedNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61f52ad2bbf7fb36, []int{1}
}

func (m *SchedNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedNameResponse.Unmarshal(m, b)
}
func (m *SchedNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedNameResponse.Marshal(b, m, deterministic)
}
func (m *SchedNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedNameResponse.Merge(m, src)
}
func (m *SchedNameResponse) XXX_Size() int {
	return xxx_messageInfo_SchedNameResponse.Size(m)
}
func (m *SchedNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchedNameResponse proto.InternalMessageInfo

func (m *SchedNameResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SchedNameResponse) GetEstablishedConnIP() []string {
	if m != nil {
		return m.EstablishedConnIP
	}
	return nil
}

func (m *SchedNameResponse) GetRemainingConnIP() []string {
	if m != nil {
		return m.RemainingConnIP
	}
	return nil
}

type UpdateResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EstablishedConnIP    []string `protobuf:"bytes,3,rep,name=EstablishedConnIP,proto3" json:"EstablishedConnIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61f52ad2bbf7fb36, []int{2}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateResponse) GetEstablishedConnIP() []string {
	if m != nil {
		return m.EstablishedConnIP
	}
	return nil
}

func init() {
	proto.RegisterType((*SchedNameRequest)(nil), "scheduler.SchedNameRequest")
	proto.RegisterType((*SchedNameResponse)(nil), "scheduler.SchedNameResponse")
	proto.RegisterType((*UpdateResponse)(nil), "scheduler.UpdateResponse")
}

func init() {
	proto.RegisterFile("server_protoctest.proto", fileDescriptor_61f52ad2bbf7fb36)
}

var fileDescriptor_61f52ad2bbf7fb36 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0x8a, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2e, 0x49, 0x2d, 0x2e, 0xd1, 0x03, 0x33,
	0x85, 0x38, 0x8b, 0x93, 0x33, 0x52, 0x53, 0x4a, 0x73, 0x52, 0x8b, 0x94, 0x96, 0x30, 0x72, 0x09,
	0x04, 0x83, 0x78, 0x7e, 0x89, 0xb9, 0xa9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42,
	0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90,
	0x0a, 0x17, 0x6f, 0x70, 0x6a, 0x4e, 0x9a, 0x67, 0x80, 0x63, 0x4a, 0x4a, 0x51, 0x6a, 0x71, 0xb1,
	0x04, 0x13, 0x58, 0x12, 0x55, 0x50, 0x48, 0x87, 0x4b, 0xd0, 0xb5, 0xb8, 0x24, 0x31, 0x29, 0x27,
	0xb3, 0x38, 0x23, 0x35, 0xc5, 0x39, 0x3f, 0x2f, 0xcf, 0x33, 0x40, 0x82, 0x59, 0x81, 0x59, 0x83,
	0x33, 0x08, 0x53, 0x42, 0x48, 0x83, 0x8b, 0x3f, 0x28, 0x35, 0x37, 0x31, 0x33, 0x2f, 0x33, 0x2f,
	0x1d, 0xaa, 0x96, 0x05, 0xac, 0x16, 0x5d, 0x58, 0xa9, 0x9e, 0x4b, 0x10, 0xc9, 0x95, 0xc5, 0x05,
	0xf9, 0x79, 0xc5, 0xa9, 0x58, 0x9d, 0x49, 0x2b, 0x07, 0x04, 0x71, 0xf1, 0x85, 0x16, 0xa4, 0x24,
	0x96, 0x50, 0xd1, 0x76, 0xa3, 0x39, 0x8c, 0x5c, 0xac, 0x60, 0x5f, 0x09, 0x79, 0x73, 0xf1, 0xb8,
	0xa7, 0x96, 0xc0, 0x7d, 0x28, 0x24, 0xad, 0x07, 0x8f, 0x21, 0x3d, 0xf4, 0xd8, 0x91, 0x92, 0xc1,
	0x2e, 0x09, 0x71, 0x96, 0x12, 0x83, 0x90, 0x1b, 0x17, 0x17, 0x28, 0x52, 0x20, 0xce, 0xc5, 0x6f,
	0x94, 0x24, 0x92, 0x24, 0xaa, 0xf7, 0x94, 0x18, 0x9c, 0x98, 0xa3, 0x18, 0xf5, 0x92, 0xd8, 0xc0,
	0x29, 0xc6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xed, 0xb7, 0x9c, 0x4c, 0x02, 0x00, 0x00,
}
